config/routes.rb
Rails.application.routes.draw do
  resources :parcellists
  resources :airinfos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  wash_out :airwebservice
end

app/models/parcellist.rb
class Parcellist < ApplicationRecord
    def self.create_new(a,b,c,d) 
        Parcellist.create(:parcelnumber => a, :name => b, :address => c, :weight => d, :isDelivery => false)
    end
end

app/controllers/parcellists_controller.rb
class ParcellistsController < ApplicationController
  before_action :set_parcellist, only: [:show, :edit, :update, :destroy]

  # GET /parcellists
  # GET /parcellists.json
  def index
    @parcellists = Parcellist.all
  end

  # GET /parcellists/1
  # GET /parcellists/1.json
  def show
  end

  # GET /parcellists/new
  def new
    @parcellist = Parcellist.new
  end

  # GET /parcellists/1/edit
  def edit
  end

  # POST /parcellists
  # POST /parcellists.json
  def create
    @parcellist = Parcellist.new(parcellist_params)

    respond_to do |format|
      if @parcellist.save
        format.html { redirect_to @parcellist, notice: 'Parcellist was successfully created.' }
        format.json { render :show, status: :created, location: @parcellist }
      else
        format.html { render :new }
        format.json { render json: @parcellist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parcellists/1
  # PATCH/PUT /parcellists/1.json
  def update
    respond_to do |format|
      if @parcellist.update(parcellist_params)
        format.html { redirect_to @parcellist, notice: 'Parcellist was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcellist }
      else
        format.html { render :edit }
        format.json { render json: @parcellist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcellists/1
  # DELETE /parcellists/1.json
  def destroy
    @parcellist.destroy
    respond_to do |format|
      format.html { redirect_to parcellists_url, notice: 'Parcellist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcellist
      @parcellist = Parcellist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parcellist_params
      params.require(:parcellist).permit(:parcelnumber, :name, :address, :weight, :isDelivery)
    end
end

app/helpers/parcellists_helper.rb
module ParcellistsHelper
end

app/views/parcellists/_form.html.erb
<%= form_with(model: parcellist, local: true) do |form| %>
  <% if parcellist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parcellist.errors.count, "error") %> prohibited this parcellist from being saved:</h2>

      <ul>
      <% parcellist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :parcelnumber %>
    <%= form.number_field :parcelnumber %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :isDelivery %>
    <%= form.check_box :isDelivery %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parcellists/edit.html.erb
<h1>Editing Parcellist</h1>

<%= render 'form', parcellist: @parcellist %>

<%= link_to 'Show', @parcellist %> |
<%= link_to 'Back', parcellists_path %>

app/views/parcellists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parcellists</h1>

<table>
  <thead>
    <tr>
      <th>Parcelnumber</th>
      <th>Name</th>
      <th>Address</th>
      <th>Weight</th>
      <th>Isdelivery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parcellists.each do |parcellist| %>
      <tr>
        <td><%= parcellist.parcelnumber %></td>
        <td><%= parcellist.name %></td>
        <td><%= parcellist.address %></td>
        <td><%= parcellist.weight %></td>
        <td><%= parcellist.isDelivery %></td>
        <td><%= link_to 'Show', parcellist %></td>
        <td><%= link_to 'Edit', edit_parcellist_path(parcellist) %></td>
        <td><%= link_to 'Destroy', parcellist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parcellist', new_parcellist_path %>

app/views/parcellists/new.html.erb
<h1>New Parcellist</h1>

<%= render 'form', parcellist: @parcellist %>

<%= link_to 'Back', parcellists_path %>

app/views/parcellists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parcelnumber:</strong>
  <%= @parcellist.parcelnumber %>
</p>

<p>
  <strong>Name:</strong>
  <%= @parcellist.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @parcellist.address %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @parcellist.weight %>
</p>

<p>
  <strong>Isdelivery:</strong>
  <%= @parcellist.isDelivery %>
</p>

<%= link_to 'Edit', edit_parcellist_path(@parcellist) %> |
<%= link_to 'Back', parcellists_path %>