config/routes.rb
Rails.application.routes.draw do
  resources :parcellists
  resources :airinfos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  wash_out :airwebservice
end

app/models/airinfo.rb
class Airinfo < ApplicationRecord
    def self.create_new(a,b,c,d) 
        Airinfo.create(:no => a, :date_t => b, :temperature => c, :humid => d)
    end
end
class AirInfomation < WashOut::Type
    map :airinfomation => [{ :no => :integer , :date => :datetime , :temp => :double , :humid => :double}]
end

class AirInfomationWithEncrypt < WashOut::Type
    map :airinfomationEncrypt => { :iv => :string , :data => :string}
end

class StudentInfo < WashOut::Type
    map :student_information => { :stdntname => :string , :stdntnumber => :integer , :hobbys => [:string] }
end

class ParcelData < WashOut::Type
    map :parcel_information => [{ :parcelnumber => :integer , :name => :string , :address => :string , :weight => :double }]
end

app/controllers/airinfos_controller.rb
class AirinfosController < ApplicationController
  before_action :set_airinfo, only: [:show, :edit, :update, :destroy]

  # GET /airinfos
  # GET /airinfos.json
  def index
    @airinfos = Airinfo.all
  end

  # GET /airinfos/1
  # GET /airinfos/1.json
  def show
  end

  # GET /airinfos/new
  def new
    @airinfo = Airinfo.new
  end

  # GET /airinfos/1/edit
  def edit
  end

  # POST /airinfos
  # POST /airinfos.json
  def create
    @airinfo = Airinfo.new(airinfo_params)

    respond_to do |format|
      if @airinfo.save
        format.html { redirect_to @airinfo, notice: 'Airinfo was successfully created.' }
        format.json { render :show, status: :created, location: @airinfo }
      else
        format.html { render :new }
        format.json { render json: @airinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airinfos/1
  # PATCH/PUT /airinfos/1.json
  def update
    respond_to do |format|
      if @airinfo.update(airinfo_params)
        format.html { redirect_to @airinfo, notice: 'Airinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @airinfo }
      else
        format.html { render :edit }
        format.json { render json: @airinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airinfos/1
  # DELETE /airinfos/1.json
  def destroy
    @airinfo.destroy
    respond_to do |format|
      format.html { redirect_to airinfos_url, notice: 'Airinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airinfo
      @airinfo = Airinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airinfo_params
      params.require(:airinfo).permit(:no, :date_t, :temperature, :humid)
    end
end

app/helpers/airinfos_helper.rb
module AirinfosHelper
end

app/views/airinfos/_form.html.erb
<%= form_with(model: airinfo, local: true) do |form| %>
  <% if airinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airinfo.errors.count, "error") %> prohibited this airinfo from being saved:</h2>

      <ul>
      <% airinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :no %>
    <%= form.number_field :no %>
  </div>

  <div class="field">
    <%= form.label :date_t %>
    <%= form.datetime_select :date_t %>
  </div>

  <div class="field">
    <%= form.label :temperature %>
    <%= form.text_field :temperature %>
  </div>

  <div class="field">
    <%= form.label :humid %>
    <%= form.text_field :humid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airinfos/edit.html.erb
<h1>Editing Airinfo</h1>

<%= render 'form', airinfo: @airinfo %>

<%= link_to 'Show', @airinfo %> |
<%= link_to 'Back', airinfos_path %>

app/views/airinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airinfos</h1>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>Date t</th>
      <th>Temperature</th>
      <th>Humid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airinfos.each do |airinfo| %>
      <tr>
        <td><%= airinfo.no %></td>
        <td><%= airinfo.date_t %></td>
        <td><%= airinfo.temperature %></td>
        <td><%= airinfo.humid %></td>
        <td><%= link_to 'Show', airinfo %></td>
        <td><%= link_to 'Edit', edit_airinfo_path(airinfo) %></td>
        <td><%= link_to 'Destroy', airinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airinfo', new_airinfo_path %>

app/views/airinfos/new.html.erb
<h1>New Airinfo</h1>

<%= render 'form', airinfo: @airinfo %>

<%= link_to 'Back', airinfos_path %>

app/views/airinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No:</strong>
  <%= @airinfo.no %>
</p>

<p>
  <strong>Date t:</strong>
  <%= @airinfo.date_t %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @airinfo.temperature %>
</p>

<p>
  <strong>Humid:</strong>
  <%= @airinfo.humid %>
</p>

<%= link_to 'Edit', edit_airinfo_path(@airinfo) %> |
<%= link_to 'Back', airinfos_path %>